// Pre-renders the gallery previews, so the landing page shows them without loading the
// typesetter or pdf.js. Rerun after changing a layout or a showcase sample:
//   npm run thumbs        (needs Python + pymupdf + Pillow)
import fs from "node:fs";
import { execFileSync } from "node:child_process";
import { SAMPLES } from "../src/model/samples";
import { ALL_FONTS, compile, renderPdf } from "../src/engine";
import { nodeBook } from "./node-fonts";

const tmp = "out/thumbs";
fs.mkdirSync(tmp, { recursive: true });
fs.mkdirSync("public/thumbs", { recursive: true });
const book = nodeBook();
await book.load(ALL_FONTS);
for (const [id, make] of Object.entries(SAMPLES)) {
  const r = make();
  fs.writeFileSync(`${tmp}/${id}.pdf`, await renderPdf(r, book, compile(r, book)));
}
const sizes = JSON.parse(execFileSync("python", ["scripts/thumbs.py", tmp, "public/thumbs"], { encoding: "utf8" }));
fs.writeFileSync("src/ui/thumbs.gen.ts", `// Generated by scripts/thumbs.ts. Do not edit by hand.
import type { TemplateId } from "../model/types";
/** Page aspect (height / width) of each pre-rendered preview. */
export const THUMB_RATIO: Record<TemplateId, number> = ${JSON.stringify(sizes)};
/** Widths available in public/thumbs/<id>-<w>.webp */
export const THUMB_WIDTHS = [500, 760] as const;
`);
console.log("thumbs:", Object.keys(sizes).join(", "));
